### ISSUE TITLE
MySQL more methods (beginTransaction, commit and rollback)

### ISSUE THREAD

**Issue by diego-G** [blueskyfish/generator-express-restful-mysql#3]
I need help to add this methods into the "db.js". I see "query" example but it is not straightforward to include the rest.

You use Q module to promisify the mysql module. Currently there are some others modules as "promise-mysql". Would it be possible to have a new template using those new modules?

**Comment by blueskyfish** [comment]
Hi Diego G. I publish the version 0.6.0 with your features. Sorry I can't test it. Please let me know if  there are some errors.
Thanks for request.

**Comment by diego-G** [comment]
Thank you very much for responding that quickly. 

Unfortunately it does not work. The three new methods you've added as prototypes they are not ready to export afterwards. Also you try to call in your example `getConnection()` which does not exist. Could you have a look?

**Comment by blueskyfish** [comment]
Hi Diego-G,
Here a gist https://gist.github.com/blueskyfish/d6f14603099ef0fd5e6b8fa802c2c267 that works. Please study the code.

**Comment by diego-G** [comment]
Thanks. I've made it!
